### ISSUE TITLE
PHP 8.1 Deprecations

### ISSUE THREAD

**Issue by BOAWEB** [akeneo/api-php-client#203]
Hi,
Is it possible to start supporting PHP 8(.1)?
There are some deprecations I'd like to see resolved.

For instance: 
`User Deprecated: Method "Iterator::current()" might add "mixed" as a native return type declaration in the future. Do the same in implementation "Akeneo\Pim\ApiClient\Pagination\ResourceCursor" now to avoid errors or add an explicit @return annotation to suppress this message.`

and:
`Deprecated: http_build_query(): Passing null to parameter #2 ($numeric_prefix) of type string is deprecated`

Maybe start a 5.0 branch?

Looking forward to this!

**Comment by tomglvng** [comment]
Hello @BOAWEB  and thank you for your contribution,

Our philosophy is to provide our PHP client with as many people as possible while keeping the highest security level; that's why the connector always uses the oldest PHP release that is supported for critical security issues.

Anyway, I had a look at your demand. I have fixed the points you noticed. You can follow the PR here: https://github.com/akeneo/api-php-client/pull/216

If you see something else, don't hesitate to open a Pull Request: we will be glad to count you as our contributor.

Regards,

The Akeneo team development
