### ISSUE TITLE
HTTPs and auto-generated certificate

### ISSUE THREAD

**Issue by nidup** [akeneo/api-php-client#73]
When using the cli with a PIM installed with an auto signed certificate, curl fails (needs to use an option to enable it).

```
"cURL error 51: SSL: no alternative certificate subject name matches target host name 'domainname.com  "
```

**Comment by LudovicTOURMAN** [comment]
api-php-client is using the class HttpClientDiscovery to retrieve an HttpClient or [create one if none is available](https://github.com/php-http/discovery/blob/1.4.0/src/ClassDiscovery.php#L192).
In the same time, Guzzle can be instanciate with a config variable defining some options (like [verify=false](http://docs.guzzlephp.org/en/stable/request-options.html#verify))
Due to HttpClientDiscovery, GuzzleHttp constructor is [created without any option](https://github.com/guzzle/guzzle/blob/master/src/Client.php#L62).

Temporary solution is to change GuzzleHttp default option in [vendor/guzzlehttp/guzzle/src/Client.php](https://github.com/guzzle/guzzle/blob/master/src/Client.php#L164) and set the `verify` to `false`

**Comment by ahocquard** [comment]
Actually, as we can"t handle every possible configuration with the discovery, it's possible to construct the client by passing the "Client" already configured the way you want.

https://github.com/akeneo/api-php-client/blob/master/src/AkeneoPimClientBuilder.php#L78

As I think it's doable this way, I close the ticket but feel free to re-open it if I'm wrong.
